### ISSUE TITLE
Feature request: import a lsdsng song into a save file

### ISSUE THREAD

**Issue by cyberic99** [alexras/pylsdj#1]
Do you plan to code such a feature?
Thx

Regards
Eric

**Comment by alexras** [comment]
Yup; it's there as of v1.3.0 (not sure how long it's been around). The function you're looking for is `load_lsdsng(filename)` in `pylsdj.project`. There's also a usage example here: https://github.com/alexras/lsmc/blob/master/lsmc/event_handlers.py#L76
