### ISSUE TITLE
.sav loading and saving is slow

### ISSUE THREAD

**Issue by alexras** [alexras/pylsdj#7]
This is probably more of a problem with bread being slow than with pylsdj itself, but something about the .sav file's structure really makes bread unhappy.

**Comment by TheOtherDays** [comment]
Would it be possible to lazy-load each project?
I mean, to list a >sav file content, we do not need to parse each song individually

**Comment by alexras** [comment]
Lazy-loading projects would help, that's true. I feel like if I fix bread's speed problem, the solution to this may just fall out. After all, we're talking about parsing 128KB here, the whole file ought to take well under a second to load.

**Comment by cyberic99** [comment]
It seems that the songs are slower and slower to load.
The last files seem to load much slower than the first ones. is it possible?

**Comment by alexras** [comment]
That's certainly a possibility; could be that some internal data structures are getting more krufty the further you get.

I'd try shuffling the songs around in the project and seeing if that impacts load time.

**Comment by alexras** [comment]
This should be a _lot_ faster in 2.3.
