### ISSUE TITLE
Ability to skip corrupted projects

### ISSUE THREAD

**Issue by cyberic99** [alexras/pylsdj#9]
I was trying to clean a corrupted .sav.
I don' t know how, but one of my songs had some '??' instead of phrases.
I tried to load the .sav file, but one fx value was outside the cirrect range, so I got an exception.
It would be great to add a flag 'ignore_corrupted_project', that would skip the corrupted project and continue to load other songs.

**Comment by alexras** [comment]
Now that lazy loading is in, presumably you could just catch the exception when the project is first referenced?

**Comment by alexras** [comment]
I feel like just catching the exception on project load is the desired behavior here, especially now that projects are being lazy-loaded.
